- name: Patching Servers
  apt:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install useful tools
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - nginx
    - python-pip
    - nmap
    - aptitude
    - traceroute
    - tree
    - atop
    - lsof
    - unzip
  become: true

