- name: Check Nomad version
  shell: |
    nomad -v | \
        grep -Pow "v(\d+\.){2}\d+" | \
        tr -d 'v'
  ignore_errors: true
  changed_when: false
  register: installed_version

- name: Check available version information
  uri:
    url: https://checkpoint-api.hashicorp.com/v1/check/nomad
    return_content: yes
  register: version_info

- name: Parse API data
  set_fact:
    version: "{{ version_info.content | regex_search('(\\d+\\.){2}\\d+') }}"

- name: Get Latest Nomad
  unarchive:
    src: "https://releases.hashicorp.com/nomad/{{ version }}/nomad_{{ version }}_linux_amd64.zip"
    dest: /bin/
    mode: 0755
    remote_src: yes
  when: ( installed_version.stdout != version ) or
        ( installed_version.rc     != 0 )
  become: true

- name: Create Nomad directory structure
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 755
  loop:
    - /etc/nomad
    - /var/lib/nomad
  become: true

- name: Configure Nomad config
  template:
    src: ../templates/nomad-client.hcl.j2
    dest: /etc/nomad/nomad-client.hcl
  become: true

- name: Configure Nomad service
  template:
    src: ../templates/nomad-client.service.j2
    dest: /etc/systemd/system/nomad-client.service
  become: true

- name: Start Nomad service
  service:
    name: nomad-client
    state: started
    enabled: yes
  become: true
